#esto es un comentario de una SOLA LINEA
""""ESTO ES UNA COMENTARIO DE 
VARIAS LINEAS"""

#ICICIALIZANDO VARIABLES 
NOMBREll="CANO PEÑA EYLEN SARAY"
EDADl=14
ESTADOl=True
NOTAl=5.0

#MOSTRAR EL CONTENIDO DE LAS VARIABLES PRINT()
print(NOMBRE)
print(EDAD)
print(ESTADO)
print(NOTA)

#QUE TIPO DE DATO CONTIENE CADA VARIABLE
print(TYPE(NOMBRE))
print(TYPE(EDAD))
print(TYPE(ESTADO))
print(Type(ESTADO))
print(TYPE(NOTA))
#VAMOS A UTILIZAR LA FUNCION INPUT PARA RECOGER DATOSPOR MEDIO DEL TECLADO.

NOMBREl=INPUT("¿COMO TE LLAMS? ")
EDADl=input("¿QUE EDAD TIENES? ")
ESTADOl=("¿EN QUE ESTADO TE ENCUENTRAS? ")
NOTAl=INPUT("¿CUAL ES TU NOTA? ")

#VISUALIZAR QUE GUARDAMOS EN LAS VARIABLES ANTERIORES
print("HOLA,"NOMBRE," UN GUSTO CONOCERTE")
print("TU EDAD ES:",EDAD)
print("TU ESTADO ES:",ESTADO)
print("TU NOTA ES:,NOTA)
